"""Change p1-p5 to String

Revision ID: 7aa4340868fd
Revises: f47ab9115ede
Create Date: 2025-01-03 00:31:45.113451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa4340868fd'
down_revision = 'f47ab9115ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.alter_column('p1',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('p2',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('p3',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('p4',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('p5',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.drop_constraint('league_p3_fkey', type_='foreignkey')
        batch_op.drop_constraint('league_p5_fkey', type_='foreignkey')
        batch_op.drop_constraint('league_p1_fkey', type_='foreignkey')
        batch_op.drop_constraint('league_p4_fkey', type_='foreignkey')
        batch_op.drop_constraint('league_p2_fkey', type_='foreignkey')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('league_p2_fkey', 'player', ['p2'], ['id'])
        batch_op.create_foreign_key('league_p4_fkey', 'player', ['p4'], ['id'])
        batch_op.create_foreign_key('league_p1_fkey', 'player', ['p1'], ['id'])
        batch_op.create_foreign_key('league_p5_fkey', 'player', ['p5'], ['id'])
        batch_op.create_foreign_key('league_p3_fkey', 'player', ['p3'], ['id'])
        batch_op.alter_column('p5',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('p4',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('p3',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('p2',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('p1',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
