"""Add order columns to Player

Revision ID: b1ba8eb4ef9d
Revises: fb5fc76bc21a
Create Date: 2025-01-01 20:16:28.521087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ba8eb4ef9d'
down_revision = 'fb5fc76bc21a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('winner_rank')
        batch_op.drop_column('loser_rank')

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('win_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('loss_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('match_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rate_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('opponent_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('achieve_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('achieve_order')
        batch_op.drop_column('opponent_order')
        batch_op.drop_column('rate_order')
        batch_op.drop_column('match_order')
        batch_op.drop_column('loss_order')
        batch_op.drop_column('win_order')

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loser_rank', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('winner_rank', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
