"""add pnpns in League

Revision ID: f47ab9115ede
Revises: 2421efdf8837
Create Date: 2025-01-02 22:22:38.317941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47ab9115ede'
down_revision = '2421efdf8837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p2p1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('p3p1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('p3p2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('p4p1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('p4p2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('p4p3', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('p5p1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('p5p2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('p5p3', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('p5p4', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.drop_column('p5p4')
        batch_op.drop_column('p5p3')
        batch_op.drop_column('p5p2')
        batch_op.drop_column('p5p1')
        batch_op.drop_column('p4p3')
        batch_op.drop_column('p4p2')
        batch_op.drop_column('p4p1')
        batch_op.drop_column('p3p2')
        batch_op.drop_column('p3p1')
        batch_op.drop_column('p2p1')

    # ### end Alembic commands ###
